const types = {
    BALANCE_BIT_UPDATE: 'BALANCE_BIT_UPDATE',
    BALANCE_ETH_UPDATE: 'BALANCE_ETH_UPDATE',
    BALANCE_BIT_SET: 'BALANCE_BIT_SET',
    BALANCE_ETH_SET: 'BALANCE_ETH_SET',
  
    UUID_SET: 'UUID_SET',
    NICK_SET: 'NICK_SET',
};
  
export default types
  